apiVersion: v1
kind: Pod
metadata:
  name: hue-scheduler
spec: 
  containers: 
  - image: tomcat:8
    name: hue-global-listener 
    volumeMounts: 
    - mountPath: /notifications 
      name: shared-volume 
  - image: httpd:2
    name: hue-job-scheduler 
    volumeMounts: 
    - mountPath: /incoming 
      name: shared-volume 
  volumes: 
  - name: shared-volume 
    emptyDir: {}